package com.jingmin.lockdemo.model;

import java.io.Serializable;
import lombok.Data;

/**
 * null
 * @TableName custmer
 */
@Data
public class Custmer implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-15 14:10:27
     */
    private Long id;

    /**
     * 
     *
     * @mbg.generated 2021-03-15 14:10:27
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table custmer
     *
     * @mbg.generated 2021-03-15 14:10:27
     */
    private static final long serialVersionUID = 1L;
}