package com.jingmin.lockdemo.model;

import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * null
 *
 * @TableName order
 */
@Data
@NoArgsConstructor
public class Order implements Serializable {
    /**
     * @mbg.generated 2021-03-15 14:10:27
     */
    private Long id;

    /**
     * @mbg.generated 2021-03-15 14:10:27
     */
    private Long custId;

    /**
     * @mbg.generated 2021-03-15 14:10:27
     */
    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated 2021-03-15 14:10:27
     */
    private static final long serialVersionUID = 1L;

    public Order(Long custId) {
        this.custId = custId;
    }
}