package com.jingmin.lockdemo.model;

import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * null
 *
 * @TableName product
 */
@Data
@NoArgsConstructor
public class Product implements Serializable {
    /**
     * @mbg.generated 2021-03-15 17:21:15
     */
    private Long id;

    /**
     * @mbg.generated 2021-03-15 17:21:15
     */
    private String name;

    /**
     * @mbg.generated 2021-03-15 17:21:15
     */
    private Long amount;

    /**
     * @mbg.generated 2021-03-15 17:21:15
     */
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated 2021-03-15 17:21:15
     */
    private static final long serialVersionUID = 1L;

    public Product(Long id, Long amount) {
        this.id = id;
        this.amount = amount;
    }
}