package com.jingmin.lockdemo.model2;

import java.io.Serializable;
import lombok.Data;

/**
 * null
 * @TableName dept
 */
@Data
public class Dept implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-17 15:38:30
     */
    private Long id;

    /**
     * 
     *
     * @mbg.generated 2021-03-17 15:38:30
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dept
     *
     * @mbg.generated 2021-03-17 15:38:30
     */
    private static final long serialVersionUID = 1L;
}